### PR TITLE
Alllow subscriber to work alone

### PR DESCRIPTION
**Pull request by jdavid**
Now by default the subscriber won't connect to a broker.
An example configuration to run an standalone subscriber has only the subscriber section:

    [subscriber]
    http = "localhost:8002"
    statedir = "state/subscriber"
    url = "http://localhost:8002"

Also added a **shared** special root, where the users can upload files. The files in **shared** will be available to all users.

And show to the user the file's size, in the list of datasets.

### CODE REVIEW

**Review by FrancescAlted — APPROVED** [review]
Adding some comments in `caterva2.sample.toml` on how to configure a standalone subscriber would be good.  Another possibility is adding a new e.g. `caterva2-standalone.sample.toml`.

Other than that, this LGTM.

**Comment by jdavid** [comment]
Added

**Comment by FrancescAlted** [comment]
One thing that I did not think about before: if there is no `publisher` section in config, where should the `root` be specified?

**Comment by jdavid** [comment]
If there's no publisher then there's no publisher's root.

The subscriber now has a shared space where users can upload files, plus their personal space (scratch). Instead of "space" we can spell it "shared root" and "scratch root"; these are specific to the subscriber.

**Pull request merged**
